_packman/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('membership/', include('django.contrib.auth.urls')),
    path('membership/', include('membership.urls')),
    path('assignments/', include('assignments.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

_project_base/urls.py
from django.contrib import admin
from django.urls import path

import pages.views

urlpatterns = [
    path('', pages.views.homepage, name='homepage'),
    path('admin/', admin.site.urls),
]

assignments/urls.py
from django.urls import path
from .views import CommitteeDetailView, CommitteesListView, DenDetailView, DenListView

urlpatterns = [
    path('committees/', CommitteesListView.as_view(), name='committees-list'),
    path('committee/<str:slug>/', CommitteeDetailView.as_view(), name='committee-detail'),
    path('dens/', DenListView.as_view(), name='dens-list'),
    path('den/<int:pk>', DenDetailView.as_view(), name='den-detail'),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('about/', views.about_page, name='about_page'),
    path('history/', views.history_page, name='history_page'),
    path('<slug:permalink>/', views.dynamic_page, name='dynamic_page'),
]

assignments/models.py
from django.db import models
from django.urls import reverse

from pages.models import DynamicPage


class Committee(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    page = models.ManyToManyField(DynamicPage, blank=True, related_name='committee')
    date_added = models.DateField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    permalink = models.SlugField(unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('committee-detail', args=[str(self.permalink)])


class Den(models.Model):
    number = models.PositiveIntegerField(primary_key=True)
    page = models.ManyToManyField(DynamicPage, blank=True, related_name='den')

    date_added = models.DateField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    BOBCAT = 1
    TIGER = 2
    WOLF = 3
    BEAR = 4
    JR_WEBE = 5
    SR_WEBE = 6
    ARROW = 7
    RANK_CHOICES = (
        (BOBCAT, "Bobcat"),
        (TIGER, "Tiger"),
        (WOLF, "Wolf"),
        (BEAR, "Bear"),
        (JR_WEBE, "Jr. Webelos"),
        (SR_WEBE, "Sr. Webelos"),
        (ARROW, "Arrow of Light"),
    )

    rank = models.PositiveSmallIntegerField(choices=RANK_CHOICES, null=True, blank=True)

    class Meta:
        ordering = ['number']

    def __str__(self):
        return 'Den {}'.format(self.number)

    def get_absolute_url(self):
        return reverse('den-detail', args=[str(self.number)])

assignments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic

from .models import Committee, Den


class CommitteeDetailView(PermissionRequiredMixin, generic.DetailView):
    permission_required = ['assignments.view_committee']
    model = Committee
    slug_field = 'permalink'


class CommitteesListView(PermissionRequiredMixin, generic.ListView):
    permission_required = ['assignments.view_committee']
    model = Committee
    paginate_by = 20


class DenDetailView(PermissionRequiredMixin, generic.DetailView):
    permission_required = ['assignments.view_den']
    model = Den
    slug_field = 'permalink'


class DenListView(PermissionRequiredMixin, generic.ListView):
    permission_required = ['assignments.view_den']
    model = Den
    paginate_by = 20

assignments/templates/assignments/committee_detail.html
{% extends "base.html" %}

{% block title %}{{ committee.name }}{% endblock %}

{% block main %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home_page' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'committees-list' %}">Committees</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ committee.name }}</li>
        </ol>
    </nav>
    <h1>{{ committee.name }}</h1>
    <div>{{ committee.description }}</div>
    {% if committee.chair.count or committee.assistant.count %}
    <h2>Leadership</h2>
        {% if committee.chair.count %}
            <h3>Chair</h3>
            <ul>
            {% for chair in committee.chair.all %}
            <li>{{ chair }}</li>
            {% endfor %}
            </ul>
            {% endif %}
        {% if committee.assistant.count %}
            <h3>Assistant</h3>
            <ul>
            {% for assistant in committee.assistant.all %}
            <li>{{ assistant }}</li>
            {% endfor %}
            </ul>
            {% endif %}
    {% endif %}

{% endblock main %}

assignments/templates/assignments/committee_list.html
{% extends 'base.html' %}

{% block title %}Committees{% endblock title %}

{% block main %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home_page' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Committees</li>
        </ol>
    </nav>
    <h1>Committees</h1>
    {% if committee_list %}
    <dl class="row">
    {% for committee in committee_list %}
        <hr>
        <dt class="col-sm-3"><a href="{{ committee.get_absolute_url }}">{{ committee }}</a></dt>
        <dd class="col-sm-9 text-truncate">{% if committee.description %}{{ committee.description }}{% endif %}</dd>
    {% endfor %}<hr>
    </dl>
    {% else %}
    <div class="alert alert-light" role="alert">No committees have been defined yet</div>
    {% endif %}
{% endblock main %}

assignments/templates/assignments/den_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ den }}{% endblock %}

{% block main %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home_page' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dens-list' %}">Dens</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ den }}</li>
        </ol>
    </nav>
    <div class="bg-white" style="height: 100px;">
        <img src="/static/img/den_{{ den.number }}_patch.jpg" class="img-fluid float-left h-75 m-2 align-middle" alt="Den {{ den.number }} patch">
        {% if den.rank %}<img src="/static/img/{{ den.get_rank_display|slugify }}.jpg" class="img-fluid h-75 m-2 align-middle" alt="{{ den.get_rank_display }} patch">{% endif %}
    </div>
    <h2>Leader{{ den.leadership.count|pluralize }}</h2>
    {% if den.leadership.count %}<ul class="list-group">
        {% for leader in den.leadership.all %}<li class="list-group-item"><a href="{{ leader.get_absolute_url }}">{{ leader }}</a></li>{% endfor %}
    </ul>
    {% else %}
    <div class="alert alert-warning" role="alert">There are no leaders assigned to this den</div>
    {% endif %}
    <h2>Member{{ den.membership.count|pluralize }}</h2>
    {% if den.membership.count %}
    <ul class="list-group">
    {% for member in den.membership.all %}
        <li class="list-group-item"><a href="{{ member.get_absolute_url }}">{{ member }}</a></li>{% endfor %}
    </ul>
    {% else %}
    <div class="alert alert-light" role="alert">This den has no members</div>
    {% endif %}
{% endblock main %}

assignments/templates/assignments/den_list.html
{% extends 'base.html' %}

{% block title %}Dens{% endblock title %}

{% block main %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home_page' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Dens</li>
        </ol>
    </nav>

    <h1>Dens</h1>
    {% if den_list %}
    <ul class="list-group">
    {% for den in den_list %}
        <li class="list-group-item">
            <a href="{{ den.get_absolute_url }}">{{ den }}</a>
            <p><small class="text-muted">{{ den.membership.count }} member{{ den.membership.count|pluralize }}</small></p>
        </li>
    {% endfor %}
    </ul>
    {% else %}
        <div class="alert alert-light" role="alert">No dens have been defined yet</div>
    {% endif %}
{% endblock main %}